-- Onboarding assessment submissions from the public /assessment form.
-- New clients fill it in before they have an account, so inserts happen
-- server-side in /api/assessment with the service-role key. RLS is enabled
-- with NO insert/update/delete policy, so the anon key can never write or
-- read these rows directly — only the coach can read them.
create table public.assessments (
  id uuid primary key default gen_random_uuid(),
  -- Generated by the browser once per form fill; the unique constraint makes
  -- a double-click / retried request land as one row instead of two.
  submission_id uuid not null unique,
  full_name text not null,
  email text not null,
  phone text not null,
  answers jsonb not null,
  created_at timestamptz not null default now()
);

create index assessments_created_at_idx on public.assessments (created_at desc);

alter table public.assessments enable row level security;

create policy "assessments_select_coach" on public.assessments for select
  using (public.is_coach());
