-- IronBodyFit meal-plan requests from the public /ironbodyfit-meal-plans form. Same
-- shape and security model as assessments (0007): inserts happen
-- server-side in /api/meal-plan with the service-role key, RLS has no
-- insert/delete policy, and only the coach can read rows. The coach can
-- also update a request to move its status along as the plan is written.
create table public.meal_plan_requests (
  id uuid primary key default gen_random_uuid(),
  -- Generated by the browser once per form fill; the unique constraint makes
  -- a double-click / retried request land as one row instead of two.
  submission_id uuid not null unique,
  full_name text not null,
  email text not null,
  phone text not null,
  answers jsonb not null,
  status text not null default 'new' check (status in ('new', 'in_progress', 'sent')),
  created_at timestamptz not null default now()
);

create index meal_plan_requests_created_at_idx on public.meal_plan_requests (created_at desc);

alter table public.meal_plan_requests enable row level security;

create policy "meal_plan_requests_select_coach" on public.meal_plan_requests for select
  using (public.is_coach());

create policy "meal_plan_requests_update_coach" on public.meal_plan_requests for update
  using (public.is_coach()) with check (public.is_coach());
